# Web details
browserName=edge
edgeDriverPath=src/main/resources/drivers/msedgedriver.exe
chromeDriverPath=src/main/resources/drivers/chrome.exe
sauceUrl=https://www.saucedemo.com/
dataTableUrl=https://datatables.net/
demoQAUrl=https://demoqa.com/upload-download
flipkartUrl=https://www.flipkart.com/